In [1]:
import os
import sys
sys.path.append('../')
from datetime import datetime, timedelta
import pandas as pd
import numpy as np
import core.config as conf

In [2]:
path = conf.data_path

In [3]:
df = pd.read_csv('../model/notebooks/result/train_past_d.csv')

In [4]:
df.head()

,act_id,iem_cd,byn_dt,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,mrz_pdt_tp_sgm_cd,lsg_sgm_cd,tco_cus_grd_cd,tot_ivs_te_sgm_cd,mrz_btp_dit_cd,iem_krl_nm,btp_cfc_cd,mkt_pr_tal_scl_tp_cd,stk_dit_cd,past_d,hist_d
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A006360,20180726,11,1,9,3,2,2,9,5,5,8,101,1,1,1,195.0,6.6
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A005930,20180131,80,1,9,3,2,2,9,5,5,8,1361,9,1,1,86.0,48.0
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A005070,20180517,5,1,9,3,2,2,9,5,5,8,2530,12,2,99,6.0,3.0
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A003520,20201112,22,1,9,3,2,2,9,5,5,8,1969,8,2,1,22.0,13.2
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A002310,20180905,324,1,9,3,2,2,9,5,5,8,1696,10,3,99,347.0,194.4

In [5]:
df.shape

(681472, 19)

In [6]:
def to_integer(dt_time):
    return 10000*dt_time.year + 100*dt_time.month + dt_time.day

In [7]:
def sell_day(buy, hold_d) :
    buy_d = str(buy)
    buy_d = datetime(int(buy_d[:4]), int(buy_d[4:6]), int(buy_d[6:]))
    sell_d = to_integer(buy_d+timedelta(days=hold_d))
    return sell_d

In [8]:
def working_day(s_dt, e_dt) : # 공휴일 제외
    s_dt = str(s_dt).split('.')[0]
    e_dt = str(e_dt).split('.')[0]
    s_dt = s_dt[:4] + '-' + s_dt[4:6] + '-' + s_dt[6:]
    e_dt = e_dt[:4] + '-' + e_dt[4:6] + '-' + e_dt[6:]
    return np.busday_count(s_dt, e_dt, weekmask='1111100')

In [9]:
df['sell_d'] = df.apply(lambda x : sell_day(x['byn_dt'], x['hold_d']), axis = 1)

In [10]:
tmp_train = df[df['sell_d'] < 20200701]

In [11]:
tmp_test = df[df['sell_d'] >= 20200701][df['byn_dt']<20200701]

/home/nyongja/anaconda3/envs/nh2021/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

In [12]:
tmp_test['hist_d'] = tmp_test.apply(lambda x : working_day(x['byn_dt'], 20200701), axis = 1 )

In [13]:
tmp_test

,act_id,iem_cd,byn_dt,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,mrz_pdt_tp_sgm_cd,lsg_sgm_cd,tco_cus_grd_cd,tot_ivs_te_sgm_cd,mrz_btp_dit_cd,iem_krl_nm,btp_cfc_cd,mkt_pr_tal_scl_tp_cd,stk_dit_cd,past_d,hist_d,sell_d
94,b6623032ed365b6c9a71c0344ebb8ca191f1ebc5927771...,A004800,20200511,83,1,6,0,3,2,5,5,6,9,3037,2,2,1,84.000000,37,20200802
96,b6623032ed365b6c9a71c0344ebb8ca191f1ebc5927771...,A009540,20200615,110,1,6,0,3,2,5,5,6,9,2848,6,1,1,115.000000,12,20201003
107,b6623032ed365b6c9a71c0344ebb8ca191f1ebc5927771...,A005160,20200601,31,1,6,0,3,2,5,5,6,9,974,10,3,99,31.000000,22,20200702
109,b6623032ed365b6c9a71c0344ebb8ca191f1ebc5927771...,A104460,20200528,63,1,6,0,3,2,5,5,6,9,1065,10,2,99,64.000000,24,20200730
114,b6623032ed365b6c9a71c0344ebb8ca191f1ebc5927771...,A064960,20200528,55,1,6,0,3,2,5,5,6,9,509,6,2,1,55.000000,24,20200722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680885,3821b3d74d3dbbd2fbade338f5c547f762c57d541c088b...,A305540,20200616,42,1,4,4,3,2,3,5,2,14,544,14,99,99,62.666667,11,20200728
680891,3821b3d74d3dbbd2fbade338f5c547f762c57d541c088b...,A315930,20200616,18,1,4,4,3,2,3,5,2,14,310,14,99,99,18.000000,11,20200704
680892,3821b3d74d3dbbd2fbade338f5c547f762c57d541c088b...,A069500,20200616,43,1,4,4,3,2,3,5,2,14,273,14,99,99,68.666667,11,20200729
680928,4006ddaa5673365096b9dd5965e20db866f6523c162f79...,A034730,20200616,27,1,5,99,5,2,5,3,2,5,481,2,1,1,27.000000,11,20200713
681243,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A012750,20200608,37,1,6,0,5,2,5,3,5,2,1813,5,1,1,61.000000,17,20200715

In [14]:
tmp_test.to_csv(path + 'tmp_test.csv', index = False)

In [ ]:
tmp_train.to_csv(path + 'tmp_train.csv', index = False)