In [1]:
import os
import sys
sys.path.append('../')

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import core.config as conf

In [2]:
train_df = pd.read_csv('../model/notebooks/result/train_data(new_past_d,new_stk_data, new_external_data, nsi).csv') # 수정필요
test_df = pd.read_csv('../model/notebooks/result/test_data(new_past_d,new_stk_data, new_external_data, nsi, new_day_external).csv')
mean_df = pd.read_csv('./result/mean_marcapdata.csv')

In [3]:
train_df.drop(['Unnamed: 0'], axis = 1, inplace = True)
test_df.drop(['Unnamed: 0'], axis = 1, inplace = True)

# [Train data 수정]

In [4]:
train_df

,act_id,iem_cd,byn_dt,hold_d,past_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,mrz_pdt_tp_sgm_cd,...,volume_d,change_d,mean_volume,mean_open,mean_high,mean_low,mean_close,mean_abs_change,date,nsi
0,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A002270,20190321,350,120.750000,2,6,4,2,2,...,2654683.0,-0.009434,3.057820e+03,587925.989405,595956.222494,579696.013040,595411.790546,0.013545,20190321,110.22
1,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A005070,20190327,19,23.250923,2,6,4,2,2,...,9399085.0,0.002558,6.215593e+05,9806.215159,10083.665037,9533.344743,10003.691117,0.026670,20190327,111.06
2,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A005930,20190320,1,58.914160,2,6,4,2,2,...,1848.0,0.000000,8.282941e+06,45025.487368,45494.950285,44570.081500,45170.081500,0.012765,20190320,108.19
3,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A033270,20190326,75,21.489474,2,6,4,2,2,...,145717.0,-0.022676,2.900570e+05,24804.080685,25477.752241,24192.547677,24917.685412,0.021596,20190326,111.85
4,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A036000,20190611,133,41.692308,2,6,4,2,2,...,1292799.0,-0.001035,2.677373e+05,5925.521597,6054.246129,5792.220864,5912.465363,0.021279,20190611,100.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681467,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A253450,20200130,130,32.022831,2,3,2,1,2,...,25117828.0,0.298450,2.364029e+05,85036.614173,86614.041995,83327.690289,84882.808399,0.020508,20200130,108.11
681468,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A264450,20201217,8,23.487805,2,3,2,1,2,...,99859.0,-0.019920,6.442973e+04,15114.947826,15477.109783,14766.867391,15119.502174,0.021951,20201217,119.96
681469,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A267320,20201007,47,8.906250,2,3,2,1,2,...,63304.0,-0.035714,1.074191e+06,1879.232102,1920.221709,1846.302540,2143.690531,0.012190,20201007,113.57
681470,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A293490,20200914,61,31.100000,2,3,2,1,2,...,351186.0,-0.001340,1.513158e+06,50502.000000,51475.333333,49558.000000,50268.666667,0.023183,20200914,106.32
681471,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A298040,20200910,3,21.328767,2,3,2,1,2,...,350790.0,0.000000,1.554243e+05,38753.733553,39688.832237,37859.194079,38696.546053,0.024884,20200910,112.01

## 1. drop open_d,volume_d,change_d,mean_volume,mean_open,mean_high,mean_low,mean_close,mean_abs_change,date

In [5]:
train_df = train_df.drop(['code','open_d','volume_d','change_d','mean_volume','mean_open','mean_high','mean_low','mean_close','mean_abs_change','date'], axis = 1)

In [6]:
train_df

,act_id,iem_cd,byn_dt,hold_d,past_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,mrz_pdt_tp_sgm_cd,...,iem_cd_te,ivs_past_d_mean,bnc_qty,tot_aet_amt,stk_par_pr,end_price,bnc_count,qty_change,aet_amt_change,nsi
0,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A002270,20190321,350,120.750000,2,6,4,2,2,...,23.014085,120.750000,1.0,667000.0,5000.0,667000.0,8.0,2.714286,923285.0,110.22
1,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A005070,20190327,19,23.250923,2,6,4,2,2,...,20.464120,23.250923,10.0,152500.0,1000.0,15250.0,2.0,10.000000,152500.0,111.06
2,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A005930,20190320,1,58.914160,2,6,4,2,2,...,35.437256,58.914160,10.0,440500.0,100.0,44050.0,2.0,10.000000,440500.0,108.19
3,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A033270,20190326,75,21.489474,2,6,4,2,2,...,15.542396,21.489474,5.0,130250.0,500.0,26050.0,4.0,7.000000,152450.0,111.85
4,0000c7a5a5a1db9c7e890da984b20d544c09cb6f51c546...,A036000,20190611,133,41.692308,2,6,4,2,2,...,34.636364,41.692308,20.0,99300.0,500.0,4965.0,4.0,60.000000,301566.0,100.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
681467,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A253450,20200130,130,32.022831,2,3,2,1,2,...,25.034257,32.022831,1.0,84700.0,500.0,84700.0,2.0,1.000000,84700.0,108.11
681468,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A264450,20201217,8,23.487805,2,3,2,1,2,...,23.287356,23.487805,2.0,52900.0,500.0,26450.0,2.0,2.000000,52900.0,119.96
681469,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A267320,20201007,47,8.906250,2,3,2,1,2,...,8.974843,8.906250,15.0,81600.0,100.0,5440.0,2.0,15.000000,81600.0,113.57
681470,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A293490,20200914,61,31.100000,2,3,2,1,2,...,12.968932,31.100000,2.0,147600.0,100.0,73800.0,5.0,2.000000,87000.0,106.32
681471,fff9cf3aaffd32dcbf70dce8e5216411f9d38537b477d6...,A298040,20200910,3,21.328767,2,3,2,1,2,...,14.015766,21.328767,15.0,1072500.0,5000.0,71500.0,2.0,15.000000,1072500.0,112.01

In [7]:
train_df.columns

Index(['act_id', 'iem_cd', 'byn_dt', 'hold_d', 'past_d', 'sex_dit_cd',
       'cus_age_stn_cd', 'ivs_icn_cd', 'cus_aet_stn_cd', 'mrz_pdt_tp_sgm_cd',
       'lsg_sgm_cd', 'tco_cus_grd_cd', 'tot_ivs_te_sgm_cd', 'mrz_btp_dit_cd',
       'iem_krl_nm', 'btp_cfc_cd', 'mkt_pr_tal_scl_tp_cd', 'stk_dit_cd',
       'hist_d', 'iem_cd_te', 'ivs_past_d_mean', 'bnc_qty', 'tot_aet_amt',
       'stk_par_pr', 'end_price', 'bnc_count', 'qty_change', 'aet_amt_change',
       'nsi'],
      dtype='object')

## 2. 날짜, 종목별 marcap data

In [8]:
# result_test[result_test.duplicated(['Code', 'Date'], keep = 'last')==True]
# result_test = result_test.drop_duplicates(['Code', 'Date'])

NameError: name 'result_test' is not defined

In [ ]:
# for i in range(len(result_test)):
#     result_test['Code'][i] = 'A' + str(result_test['Code'][i])
#     result_test['Date'][i] = result_test['Date'][i].replace('-', '')

In [ ]:
# test_df = pd.merge(test_df, result_test, how = 'left', left_on = ['iem_cd', 'byn_dt'], right_on = ['Code', 'Date'])

# [Test data 수정]

In [9]:
test_df

,act_id,iem_cd,byn_dt,hist_d,submit_id,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,...,changes_d,changesratio_d,open_d,high_d,low_d,volume_d,amount_d,marcap_d,stocks_d,rank_d
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A032640,20200522,153,IDX00001,0,1,9,3,2,...,-200.0,-1.50,13300.0,13450.0,13050.0,1930122.0,2.559558e+10,5.741439e+12,436611361.0,38.0
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A160600,20190823,335,IDX00002,0,1,9,3,2,...,-200.0,-1.54,13000.0,13300.0,12350.0,1783575.0,2.283939e+10,1.521337e+11,11932056.0,824.0
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A234340,20200611,139,IDX00003,0,1,9,3,2,...,-500.0,-1.58,31600.0,31750.0,30450.0,241315.0,7.448385e+09,2.882037e+11,9267000.0,548.0
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A131760,20200120,236,IDX00004,0,1,9,3,2,...,190.0,9.18,2100.0,2285.0,2070.0,6615258.0,1.457208e+10,9.700838e+10,42924063.0,1280.0
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A293490,20201217,9,IDX00005,0,1,9,3,2,...,100.0,0.22,46350.0,46850.0,46200.0,523303.0,2.432441e+10,3.439698e+12,74051634.0,89.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70591,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A000810,20201127,23,IDX70592,0,1,6,0,5,...,-4500.0,-2.22,207000.0,210000.0,198500.0,546159.0,1.106830e+11,9.403905e+12,47374837.0,35.0
70592,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A005945,20200731,103,IDX70593,0,1,6,0,5,...,-40.0,-0.53,7500.0,7500.0,7410.0,79055.0,5.876391e+08,1.404000e+11,18870968.0,1021.0
70593,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A004740,20170704,858,IDX70594,0,1,4,4,2,...,2.0,4.26,52.0,57.0,38.0,65023719.0,3.252413e+09,3.524347e+09,71925448.0,2245.0
70594,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A001630,20201215,11,IDX70595,0,1,4,4,2,...,-3500.0,-2.86,124000.0,128000.0,117500.0,509014.0,6.232090e+10,5.961735e+11,5009861.0,361.0
70595,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A185750,20201224,4,IDX70596,0,1,4,4,2,...,4000.0,1.79,224500.0,231000.0,217000.0,366729.0,8.240066e+10,2.481936e+12,10885685.0,119.0

In [10]:
test_df.columns

Index(['act_id', 'iem_cd', 'byn_dt', 'hist_d', 'submit_id', 'hold_d',
       'sex_dit_cd', 'cus_age_stn_cd', 'ivs_icn_cd', 'cus_aet_stn_cd',
       'mrz_pdt_tp_sgm_cd', 'lsg_sgm_cd', 'tco_cus_grd_cd',
       'tot_ivs_te_sgm_cd', 'mrz_btp_dit_cd', 'iem_krl_nm', 'btp_cfc_cd',
       'mkt_pr_tal_scl_tp_cd', 'stk_dit_cd', 'past_d', 'iem_cd_te', 'bnc_qty',
       'tot_aet_amt', 'stk_par_pr', 'end_price', 'bnc_count', 'qty_change',
       'aet_amt_change', 'mean_low', 'nsi', 'close_d', 'changes_d',
       'changesratio_d', 'open_d', 'high_d', 'low_d', 'volume_d', 'amount_d',
       'marcap_d', 'stocks_d', 'rank_d'],
      dtype='object')

In [11]:
test_df = test_df.drop(['mean_low'], axis=1)

In [12]:
test_df

,act_id,iem_cd,byn_dt,hist_d,submit_id,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,...,changes_d,changesratio_d,open_d,high_d,low_d,volume_d,amount_d,marcap_d,stocks_d,rank_d
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A032640,20200522,153,IDX00001,0,1,9,3,2,...,-200.0,-1.50,13300.0,13450.0,13050.0,1930122.0,2.559558e+10,5.741439e+12,436611361.0,38.0
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A160600,20190823,335,IDX00002,0,1,9,3,2,...,-200.0,-1.54,13000.0,13300.0,12350.0,1783575.0,2.283939e+10,1.521337e+11,11932056.0,824.0
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A234340,20200611,139,IDX00003,0,1,9,3,2,...,-500.0,-1.58,31600.0,31750.0,30450.0,241315.0,7.448385e+09,2.882037e+11,9267000.0,548.0
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A131760,20200120,236,IDX00004,0,1,9,3,2,...,190.0,9.18,2100.0,2285.0,2070.0,6615258.0,1.457208e+10,9.700838e+10,42924063.0,1280.0
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A293490,20201217,9,IDX00005,0,1,9,3,2,...,100.0,0.22,46350.0,46850.0,46200.0,523303.0,2.432441e+10,3.439698e+12,74051634.0,89.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70591,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A000810,20201127,23,IDX70592,0,1,6,0,5,...,-4500.0,-2.22,207000.0,210000.0,198500.0,546159.0,1.106830e+11,9.403905e+12,47374837.0,35.0
70592,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A005945,20200731,103,IDX70593,0,1,6,0,5,...,-40.0,-0.53,7500.0,7500.0,7410.0,79055.0,5.876391e+08,1.404000e+11,18870968.0,1021.0
70593,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A004740,20170704,858,IDX70594,0,1,4,4,2,...,2.0,4.26,52.0,57.0,38.0,65023719.0,3.252413e+09,3.524347e+09,71925448.0,2245.0
70594,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A001630,20201215,11,IDX70595,0,1,4,4,2,...,-3500.0,-2.86,124000.0,128000.0,117500.0,509014.0,6.232090e+10,5.961735e+11,5009861.0,361.0
70595,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A185750,20201224,4,IDX70596,0,1,4,4,2,...,4000.0,1.79,224500.0,231000.0,217000.0,366729.0,8.240066e+10,2.481936e+12,10885685.0,119.0

# test_df ivs_past_d_mean 붙이기

In [13]:
ivs_past_df = pd.read_csv('../data/'+ 'preprocessing/ivs_past_d_mean.csv') # 영미

In [14]:
ivs_past_df

        iem_cd  ivs_past_d_mean  ivs_icn_cd
0      A000020        30.428571           0
1      A000030       603.000000           0
2      A000040         8.400000           0
3      A000060        68.833333           0
4      A000080        26.125000           0
...        ...              ...         ...
16726  A367380        24.444444          99
16727  A367770        12.500000          99
16728  A368200        17.000000          99
16729  A368590        15.666667          99
16730  A368680        18.000000          99

[16731 rows x 3 columns]

In [15]:
test_df = pd.merge(left = test_df, right= ivs_past_df, how='left', on=['iem_cd', 'ivs_icn_cd'])

In [16]:
test_df

,act_id,iem_cd,byn_dt,hist_d,submit_id,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,...,changesratio_d,open_d,high_d,low_d,volume_d,amount_d,marcap_d,stocks_d,rank_d,ivs_past_d_mean
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A032640,20200522,153,IDX00001,0,1,9,3,2,...,-1.50,13300.0,13450.0,13050.0,1930122.0,2.559558e+10,5.741439e+12,436611361.0,38.0,42.099138
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A160600,20190823,335,IDX00002,0,1,9,3,2,...,-1.54,13000.0,13300.0,12350.0,1783575.0,2.283939e+10,1.521337e+11,11932056.0,824.0,42.136364
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A234340,20200611,139,IDX00003,0,1,9,3,2,...,-1.58,31600.0,31750.0,30450.0,241315.0,7.448385e+09,2.882037e+11,9267000.0,548.0,33.936508
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A131760,20200120,236,IDX00004,0,1,9,3,2,...,9.18,2100.0,2285.0,2070.0,6615258.0,1.457208e+10,9.700838e+10,42924063.0,1280.0,38.292308
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A293490,20201217,9,IDX00005,0,1,9,3,2,...,0.22,46350.0,46850.0,46200.0,523303.0,2.432441e+10,3.439698e+12,74051634.0,89.0,27.115854
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70591,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A000810,20201127,23,IDX70592,0,1,6,0,5,...,-2.22,207000.0,210000.0,198500.0,546159.0,1.106830e+11,9.403905e+12,47374837.0,35.0,8.428571
70592,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A005945,20200731,103,IDX70593,0,1,6,0,5,...,-0.53,7500.0,7500.0,7410.0,79055.0,5.876391e+08,1.404000e+11,18870968.0,1021.0,127.333333
70593,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A004740,20170704,858,IDX70594,0,1,4,4,2,...,4.26,52.0,57.0,38.0,65023719.0,3.252413e+09,3.524347e+09,71925448.0,2245.0,457.500000
70594,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A001630,20201215,11,IDX70595,0,1,4,4,2,...,-2.86,124000.0,128000.0,117500.0,509014.0,6.232090e+10,5.961735e+11,5009861.0,361.0,29.958333
70595,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A185750,20201224,4,IDX70596,0,1,4,4,2,...,1.79,224500.0,231000.0,217000.0,366729.0,8.240066e+10,2.481936e+12,10885685.0,119.0,29.320312

In [17]:
mean_df['code'] = mean_df.apply(lambda x : 'A' + x['code'], axis = 1)

In [18]:
mean_df

,code,mean_close,mean_changes,mean_chagesratio,mean_open,mean_high,mean_low,mean_volume,mean_amount,mean_marcap,mean_stocks,mean_rank
0,A000020,10963.236735,244.081633,2.04094693877551,10978.391837,11248.922449,10730.946939,4.718209e+05,7.580070e+09,3.062193e+11,2.793147e+07,533.499592
1,A000030,14610.736950,174.155578,1.1926816786079837,14602.886387,14765.936540,14441.402252,1.596502e+06,2.326846e+10,9.876858e+12,6.760000e+08,34.430911
2,A000040,756.496228,16.001676,2.1158088851634536,757.409891,776.373009,738.655490,1.335930e+06,1.167793e+09,1.064223e+11,1.381645e+08,1285.624476
3,A000050,38899.265677,637.186469,1.6034653465346536,38884.735974,39609.249175,38176.815182,4.083990e+04,6.782175e+08,3.811369e+11,2.358799e+07,439.003300
4,A000060,18241.289796,226.073469,1.2557714285714283,18244.571429,18468.685714,17999.004082,1.785742e+05,3.245016e+09,2.030308e+12,1.113897e+08,122.334694
...,...,...,...,...,...,...,...,...,...,...,...,...
2748,A950160,43870.912548,1278.897338,2.900228136882129,43989.448669,45218.060837,42891.444867,7.894817e+05,3.944129e+10,2.667335e+12,6.082304e+07,105.125475
2749,A950170,8409.942244,263.597360,2.9135148514851483,8437.491749,8687.483498,8185.123762,4.681572e+05,5.764655e+09,2.943944e+11,3.500552e+07,623.379538
2750,A950180,15233.870968,388.104839,2.384798387096774,15245.766129,15637.298387,14872.983871,2.967502e+05,5.963529e+09,3.208527e+11,2.106180e+07,525.060484
2751,A950190,28148.369565,558.695652,1.954891304347826,28253.804348,28729.891304,27664.673913,3.223562e+05,9.554281e+09,3.628210e+11,1.288959e+07,528.152174
2752,A950200,16597.008547,717.521368,4.421196581196581,16726.068376,17635.470085,16071.794872,2.517472e+06,4.912344e+10,2.980208e+11,1.797333e+07,620.068376

In [ ]:
#train_df = pd.merge(left = train_df, right = mean_df, how='left', left_on='iem_cd', right_on='code')

In [19]:
test_df = pd.merge(left = test_df, right = mean_df, how='left', left_on='iem_cd', right_on='code')

In [20]:
test_df

,act_id,iem_cd,byn_dt,hist_d,submit_id,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,...,mean_changes,mean_chagesratio,mean_open,mean_high,mean_low,mean_volume,mean_amount,mean_marcap,mean_stocks,mean_rank
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A032640,20200522,153,IDX00001,0,1,9,3,2,...,204.955102,1.5254122448979592,13354.857143,13562.930612,13151.934694,1.962516e+06,2.679157e+10,5.828765e+12,4.366114e+08,49.962449
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A160600,20190823,335,IDX00002,0,1,9,3,2,...,141.274225,1.832684108527132,7915.473837,8064.566860,7725.437984,1.384620e+05,9.123101e+08,8.349173e+10,1.194359e+07,1376.468023
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A234340,20200611,139,IDX00003,0,1,9,3,2,...,626.411290,2.3936290322580644,27909.475806,28554.233871,27226.612903,1.567751e+05,4.386265e+09,2.583251e+11,9.267000e+06,621.036290
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A131760,20200120,236,IDX00004,0,1,9,3,2,...,112.877551,2.3855183673469385,4818.085714,4938.906122,4694.310204,4.928966e+05,1.680491e+09,5.477783e+10,1.619415e+07,1705.037551
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A293490,20201217,9,IDX00005,0,1,9,3,2,...,1473.333333,2.6869333333333336,50502.000000,51475.333333,49558.000000,1.513158e+06,9.027361e+10,3.704826e+12,7.372998e+07,75.840000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70591,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A000810,20201127,23,IDX70592,0,1,6,0,5,...,2982.448980,1.1951755102040815,258979.183673,262030.612245,256299.591837,9.183918e+04,2.276884e+10,1.227888e+13,4.737484e+07,26.735510
70592,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A005945,20200731,103,IDX70593,0,1,6,0,5,...,70.269388,0.8591428571428572,8254.269388,8316.457143,8173.069388,7.037090e+04,5.848667e+08,1.557289e+11,1.887097e+07,877.355102
70593,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A004740,20170704,858,IDX70594,0,1,4,4,2,...,132.000000,26.01571428571429,93.571429,98.857143,74.285714,4.848112e+07,4.177086e+09,5.692385e+09,7.192545e+07,2215.000000
70594,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A001630,20201215,11,IDX70595,0,1,4,4,2,...,1431.510204,1.636791836734694,81466.285714,82966.448980,79991.428571,3.030065e+04,3.193889e+09,4.019397e+11,4.949485e+06,422.361633
70595,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A185750,20201224,4,IDX70596,0,1,4,4,2,...,2431.428571,1.9854938775510205,117923.346939,120466.367347,115612.734694,9.419701e+04,1.419343e+10,1.165016e+12,9.858283e+06,183.500408

In [21]:
test_df.columns

Index(['act_id', 'iem_cd', 'byn_dt', 'hist_d', 'submit_id', 'hold_d',
       'sex_dit_cd', 'cus_age_stn_cd', 'ivs_icn_cd', 'cus_aet_stn_cd',
       'mrz_pdt_tp_sgm_cd', 'lsg_sgm_cd', 'tco_cus_grd_cd',
       'tot_ivs_te_sgm_cd', 'mrz_btp_dit_cd', 'iem_krl_nm', 'btp_cfc_cd',
       'mkt_pr_tal_scl_tp_cd', 'stk_dit_cd', 'past_d', 'iem_cd_te', 'bnc_qty',
       'tot_aet_amt', 'stk_par_pr', 'end_price', 'bnc_count', 'qty_change',
       'aet_amt_change', 'nsi', 'close_d', 'changes_d', 'changesratio_d',
       'open_d', 'high_d', 'low_d', 'volume_d', 'amount_d', 'marcap_d',
       'stocks_d', 'rank_d', 'ivs_past_d_mean', 'code', 'mean_close',
       'mean_changes', 'mean_chagesratio', 'mean_open', 'mean_high',
       'mean_low', 'mean_volume', 'mean_amount', 'mean_marcap', 'mean_stocks',
       'mean_rank'],
      dtype='object')

In [22]:
test_df=test_df.drop(['code'],axis=1)

In [23]:
test_df

,act_id,iem_cd,byn_dt,hist_d,submit_id,hold_d,sex_dit_cd,cus_age_stn_cd,ivs_icn_cd,cus_aet_stn_cd,...,mean_changes,mean_chagesratio,mean_open,mean_high,mean_low,mean_volume,mean_amount,mean_marcap,mean_stocks,mean_rank
0,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A032640,20200522,153,IDX00001,0,1,9,3,2,...,204.955102,1.5254122448979592,13354.857143,13562.930612,13151.934694,1.962516e+06,2.679157e+10,5.828765e+12,4.366114e+08,49.962449
1,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A160600,20190823,335,IDX00002,0,1,9,3,2,...,141.274225,1.832684108527132,7915.473837,8064.566860,7725.437984,1.384620e+05,9.123101e+08,8.349173e+10,1.194359e+07,1376.468023
2,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A234340,20200611,139,IDX00003,0,1,9,3,2,...,626.411290,2.3936290322580644,27909.475806,28554.233871,27226.612903,1.567751e+05,4.386265e+09,2.583251e+11,9.267000e+06,621.036290
3,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A131760,20200120,236,IDX00004,0,1,9,3,2,...,112.877551,2.3855183673469385,4818.085714,4938.906122,4694.310204,4.928966e+05,1.680491e+09,5.477783e+10,1.619415e+07,1705.037551
4,0ad104dbed99be0cd858aa772765ddedade554601a981b...,A293490,20201217,9,IDX00005,0,1,9,3,2,...,1473.333333,2.6869333333333336,50502.000000,51475.333333,49558.000000,1.513158e+06,9.027361e+10,3.704826e+12,7.372998e+07,75.840000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70591,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A000810,20201127,23,IDX70592,0,1,6,0,5,...,2982.448980,1.1951755102040815,258979.183673,262030.612245,256299.591837,9.183918e+04,2.276884e+10,1.227888e+13,4.737484e+07,26.735510
70592,564af3cf975ed4fa05148ada689d5002e9c2d43dee9481...,A005945,20200731,103,IDX70593,0,1,6,0,5,...,70.269388,0.8591428571428572,8254.269388,8316.457143,8173.069388,7.037090e+04,5.848667e+08,1.557289e+11,1.887097e+07,877.355102
70593,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A004740,20170704,858,IDX70594,0,1,4,4,2,...,132.000000,26.01571428571429,93.571429,98.857143,74.285714,4.848112e+07,4.177086e+09,5.692385e+09,7.192545e+07,2215.000000
70594,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A001630,20201215,11,IDX70595,0,1,4,4,2,...,1431.510204,1.636791836734694,81466.285714,82966.448980,79991.428571,3.030065e+04,3.193889e+09,4.019397e+11,4.949485e+06,422.361633
70595,4561928f2825f6389f228088ac807a9fb4575ffdcbc47a...,A185750,20201224,4,IDX70596,0,1,4,4,2,...,2431.428571,1.9854938775510205,117923.346939,120466.367347,115612.734694,9.419701e+04,1.419343e+10,1.165016e+12,9.858283e+06,183.500408

In [24]:
#train_df.to_csv('../model/notebooks/result/train_data(new_past_d,new_stk_data, new_external_data, nsi).csv', index=False) # 수정필요
test_df.to_csv('../model/notebooks/result/test_data(new_past_d,new_stk_data, nsi, new_day_external, marcap_external).csv', index=False)
#mean_df = pd.read_csv('./result/mean_marcapdata.csv')